---
.gitignore:
  paths:
    - .coverage
    - .librarian
    - .kitchen
    - .tmp
    - .bundle
    - /cover/
    - /ci/
    - Puppetfile.lock
.gitlab-ci.yml:
  # we don't use GitLab
  unmanaged: true
# .travis.yml:
#   # we keep our own .travis.yml because of integration testing
#   unmanaged: true
# appveyor.yml:
#   # we don't use Appveyor
#   unmanaged: true
Gemfile:
  required:
    ':development':
      - gem: 'puppet-lint-absolute_classname-check'
        version: '>= 1.0.0'
      - gem: 'puppet-lint-absolute_template_path'
        version: '>= 1.0.1'
      - gem: 'puppet-lint-alias-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-classes_and_types_beginning_with_digits-check'
        version: '>= 0.1.2'
      - gem: 'puppet-lint-concatenated_template_files-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-file_ensure-check'
        version: '>= 0.3.1'
      - gem: 'puppet-lint-file_source_rights-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-leading_zero-check'
        version: '>= 0.1.1'
      - gem: 'puppet-lint-resource_reference_syntax'
        version: '>= 1.0.10'
      - gem: 'puppet-lint-trailing_comma-check'
        version: '>= 0.3.2'
      - gem: 'puppet-lint-unquoted_string-check'
        version: '>= 0.3.0'
      - gem: 'puppet-lint-version_comparison-check'
        version: '>= 0.2.1'
Rakefile:
  extras:
    - 'PuppetLint.configuration.absolute_classname_reverse = true'
spec/spec_helper.rb:
  mock_with: ':rspec'
.travis.yml:
  deploy_to_forge:
    enabled: true
  user: encore
  secure: "vSTtY4V1DYCk7nOGoPiy7KvgXalpUZ7JXpzjFF99X76YlgE1bHPjWT9pEoHq0pNhQlNW7nBE42xkGVeb9EJjzrmlG/HMFUz1VvQ+twHeAGBMWllzW4XkthwJ3BiLxwzdmf8WjGTbKAUNVMKi6t3N+98IobHIlINPdtuHPqRH6b3CwAp++xnkKcj8lgzcg8KrB7Th4pGcmzmBrDRhRyZcaSpUkDwHfBIIOo+QVw++iIAIYi93y6gnlXD/xTR144mdO6u/5QKCaD6MUxf8o1uWrP5w1iZNNLqLeM1QpHfpA4Ka/v3+eLqD0PLPfIA2LM0F3k6yz5cLhQ2gyMWlwfd+siaaUw2EM4qhmQVg1BTjYP6/uvf1/nCvTbEU5+7+izpp7t+pY0CMsNCKGsoGB1TrI5U93l07FqNxQ2kmfQ2bl6dYAO4qtpWLBNkv3mm+1nWF/eh/SlNmY6syO/tT+br6DruXGmISceEXcmkbZoLdDfs2e3hDCMeQgfeeqs1CvCXKl3hmzw8BkSaMZBPWhGDthF1lt8xFiZmiuLmZFrsG8avXpd/JPeH76X2ZqoWPT+Bzwou0S5nT5Pv7d1FYeR907TBNB3MGb+omrTcdSgW/wHY6EcXAa2yMoOynQ42mrNoeFaSM6rd3bDPyHWtmG1ciaRldCd/R9mT5kp7nXkcNvMA="

